### ISSUE TITLE
Creating a status throws an error

### ISSUE THREAD

**Issue by logg** [bterlson/redmine-status-updates#2]
It's complaining about a missing erb file. I see that your mailer files are identical to the ones in redmine so I would assume that they should work. 

Rails 2.2.2
Ruby 1.8.7

**Error**

ActionView::MissingTemplate (Missing template status_mailer/realtime_notification.erb in view path /home/deploy/www/redmine/current/vendor/plugins/stuff_to_do_plugin/app/views:/home/deploy/www/redmine/current/vendor/plugins/redmine_status/app/views:/home/deploy/www/redmine/current/vendor/plugins/question_plugin/app/views:/home/deploy/www/redmine/current/app/views:/home/deploy/www/redmine/current/app/views:):
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/template.rb:95:in `find_full_path'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/template.rb:16:in`initialize'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/base.rb:332:in `new'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/base.rb:332:in`_unmemoized__pick_template'
    /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/memoizable.rb:70:in `_pick_template'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/base.rb:256:in`render'
    /usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:564:in `render'
    /app/models/mailer.rb:336:in`render_message'
    /usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:496:in `create!'
    /usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:455:in`initialize'
    /usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:392:in `new'
    /usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:392:in`method_missing'
    /vendor/plugins/redmine_status/app/models/status_observer.rb:5:in `after_create'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/observer.rb:171:in`send'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/observer.rb:171:in `update'
    /usr/local/lib/ruby/1.8/observer.rb:185:in`notify_observers'
    /usr/local/lib/ruby/1.8/observer.rb:184:in `each'
    /usr/local/lib/ruby/1.8/observer.rb:184:in`notify_observers'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/callbacks.rb:328:in `notify'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/callbacks.rb:321:in`callback'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/callbacks.rb:238:in `create_without_timestamps'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/timestamp.rb:29:in`create'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:2699:in `create_or_update_without_callbacks'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/callbacks.rb:222:in`create_or_update'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:2383:in `save_without_validation'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/validations.rb:1009:in`save_without_dirty'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/dirty.rb:79:in `save_without_transactions'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:179:in`send'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:179:in `with_transaction_returning_status'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in`transaction'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:129:in `transaction'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:138:in`transaction'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:178:in `with_transaction_returning_status'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:146:in`save'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:158:in `rollback_active_record_state!'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:146:in`save'
    /vendor/plugins/redmine_status/app/controllers/statuses_controller.rb:28:in `create'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in`send'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in `perform_action_without_filters'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:617:in`call_filters'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
    /usr/local/lib/ruby/1.8/benchmark.rb:293:in `measure'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/rescue.rb:136:in `perform_action_without_caching'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/caching/sql_cache.rb:13:in`perform_action'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
    /usr/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/query_cache.rb:8:in`cache'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/caching/sql_cache.rb:12:in `perform_action'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:524:in`send'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:524:in `process_without_filters'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:606:in`process_without_session_management_support'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/session_management.rb:134:in `process'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:392:in`process'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:183:in `handle_request'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:110:in`dispatch_unlocked'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:123:in `dispatch'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:122:in`synchronize'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:122:in `dispatch'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:132:in`dispatch_cgi'
    /usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:39:in `dispatch'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/rack/adapter/rails.rb:54:in`serve_rails'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/rack/adapter/rails.rb:74:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/connection.rb:63:in`pre_process'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/connection.rb:54:in `process'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/connection.rb:39:in`receive_data'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.2/lib/eventmachine.rb:231:in `run_machine'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.2/lib/eventmachine.rb:231:in`run'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/backends/base.rb:57:in `start'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/server.rb:150:in`start'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/controllers/controller.rb:80:in `start'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/runner.rb:173:in`send'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/runner.rb:173:in `run_command'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/lib/thin/runner.rb:139:in`run!'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.0.0/bin/thin:6
    /usr/local/bin/thin:19:in `load'
    /usr/local/bin/thin:19

**Comment by bterlson** [comment]
I pushed a fix that will hopefully address this problem. It's due to an engines bug with Rails 2.2.2, the version included in Redmine. Let me know if this helps!

**Comment by logg** [comment]
Thanks, I'll check it out this evening and will let you know how it turns out.

**Comment by dp-naw** [comment]
In your last update, filenames on lines 8,11,25, and 28 in status_mailer.rb should end with rhtml instead of erb. 
So line 8:       

<pre>
:body => render_message("realtime_notification.text.html.rhtml", :author => status.user, :message => status.message)
</pre>

Sorry, i have no time to figure out if i can commit that change myself somehow.
Cheers,
-D

**Comment by bterlson** [comment]
Ugh, thanks. I'll update it right now.
